version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes: 
       - ./public_html:/var/www/html
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     ports: 
       - "8081:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
       - wpsite
 
   db: 
     image: mariadb:latest
     command: mysqld --innodb-buffer-pool-size=64M
     volumes:
       - ./database:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: my_root_pass12345
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - wpsite

   phpmyadmin:
     depends_on:
      - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
      - '8080:80'
     environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_root_pass12345 
     networks:
      - wpsite
     
   nginx:
     depends_on:
      - wordpress
     image: nginx:alpine
     restart: always
     ports:
      - '80:80'
     volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
     networks:
      - wpsite

   redis: 
     image: redis
     restart: always
     ports:
      - '6379:6379'
     networks:
      - wpsite

networks:
  wpsite:
volumes:
  database:
  public_html: 
